### ISSUE TITLE
ImportError: cannot import name 'FlaskMuck' from 'flask_muck.views'

### ISSUE THREAD

**Issue by dragonballa** [dtiesling/flask-muck#95]
Tried the sample code on the readme, I installed flask-muck via pip3

```
Traceback (most recent call last):
  File "/Users/me/dev/a/index.py", line 2, in <module>
    from flask_muck.views import FlaskMuckApiView, FlaskMuck
ImportError: cannot import name 'FlaskMuck' from 'flask_muck.views' (/opt/homebrew/lib/python3.10/site-packages/flask_muck/views.py)
```

**Comment by dtiesling** [comment]
Oh no, docs may have gotten out of date. I'll test everything tonight and make updates if necessary.

**Comment by dtiesling** [comment]
@dragonballa I forgot to mention that the docs should be up to date. The Quickstart is here - https://dtiesling.github.io/flask-muck/stable/quickstart/

**Comment by dtiesling** [comment]
Readme has been updated to fix the import path error and to be more clear that it is code to show how the library works but not a full working example app.
